substitutions:
  name: sonoff-rf-bridge
  friendly_name: Sonoff RF Bridge

.protocol_config: &protocol_config
  pulse_length: 300
  sync: [1, 16]
  zero: [1, 3]
  one: [3, 1]
  inverted: false

.repeat_config: &repeat_config
  times: 5
  wait_time: 0ms

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  comment: Sonoff RF Bridge R2 - Simple RF Bridge

esp8266:
  board: esp8285

logger:

ota:
  platform: esphome
  password: !secret sonoff_rf_bridge_ota_pwd

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:
  encryption:
    key: !secret sonoff_rf_bridge_encryption_key
  services:
    - service: send_ft0317a_rf_code
      variables:
        code_a: string
        code_b: string
      then:
        - remote_transmitter.transmit_rc_switch_raw:
            code: !lambda 'return code_a;'
            protocol: *protocol_config
            repeat: *repeat_config
        - delay: 33ms
        - remote_transmitter.transmit_rc_switch_raw:
            code: !lambda 'return code_b;'
            protocol: *protocol_config
            repeat: *repeat_config

remote_receiver:
  pin: 4
  dump: rc_switch
  on_rc_switch:
    then:
      - lambda: |-
          std::string received_code = "";
          uint64_t code = x.code;
          for (int i = 39; i >= 0; i--) {
            received_code += ((code >> i) & 1) ? "1" : "0";
          }
          
          ESP_LOGD("main", "Received raw RF code: %s", received_code.c_str());
          
      - homeassistant.event:
          event: esphome.ft0317a_rf_code_received
          data:
            raw_code: !lambda |-
              std::string received_code = "";
              uint64_t code = x.code;
              for (int i = 39; i >= 0; i--) {
                received_code += ((code >> i) & 1) ? "1" : "0";
              }
              return received_code;

remote_transmitter:
  pin: 5
  carrier_duty_percent: 100%

status_led:
  pin:
    number: GPIO13
    inverted: false